version: "2"
linters:
  default: all
  disable:
    - noinlineerr
    - depguard
    - ireturn
    - gochecknoglobals
    # deprecated
    - wsl
  settings:
    funcorder:
      constructor: false
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 140
    misspell:
      locale: US
    varnamelen:
      min-name-length: 2
      ignore-decls:
        - w io.Writer
        - t testing.T
        - e error
        - i int
        - b bytes.Buffer
        - h Handle
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - exhaustivestruct
          - exhaustruct
          - funlen
          - mnd
          - tenv
          - varnamelen
          - wrapcheck
        path: _test\.go
      - linters:
          - exhaustivestruct
          - exhaustruct
          - mnd
          - varnamelen
          - wrapcheck
        path: test/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  default: all
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
