name: Go Action 

on:
  push:
    branches:
      - master
    paths:
      - 'provider/etcd/**'
      - '.gitea/workflows/etcd.yml'
  pull_request:
    paths:
      - 'provider/etcd/**'
      - '.gitea/workflows/etcd.yml'

jobs:
  goaction:
    runs-on: ubuntu-latest # Use a Gitea Actions runner label
    services:
      # The label "etcd-server" becomes the hostname for the service.
      etcd-server:
        # Use the official etcd Docker image
        image: quay.io/coreos/etcd:v3.6.7
        env:
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379 
          ETCD_ADVERTISE_CLIENT_URLS: http://etcd-server:2379 

    env:
      FDEVS_CONFIG_ETCD_HOST: 'etcd-server:2379'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4 # Action to clone the repo

      - name: Set up Go
        uses: actions/setup-go@v5 # Action to install a specific Go version
        with:
          go-version: '1.25.5' # Specify your required Go version
      
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8 # Use the golangci-lint action
        with:
          version: v2.7.2 # Specify the linter version
          # Optional: additional arguments
          args: --verbose
          working-directory: ./provider/etcd 

      - name: Run go test
        run: go test ./...
        working-directory: ./provider/etcd

